AWSTemplateFormatVersion: "2010-09-09"
Description: Manage EBS snapshots automatically
Parameters:
  FrequencyTagName:
    Type: String
    Default: Snapshot Frequency
    Description: The tag to look for on instances whose volumes should be automatically snapshotted.
  RetentionTagName:
    Type: String
    Default: Snapshot Retention
    Description: The tag to use for deciding snapshot retention values.
  DefaultRetention:
    Type: String
    Default: 14d
    Description: The default retention to apply to instance volumes if the retention tag is not specified.
Resources:
  EbsVolumeQueue:
    # The queue to place volume ids that need to be examined into.
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120
  LambdaRole:
    # Permissions needed by the instance-manager Lambda function.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: EC2-Permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateSnapshot
                  - ec2:CreateTags
                  - ec2:DeleteSnapshot
                  - ec2:DescribeInstances
                  - ec2:DescribeSnapshots
                Resource: "*"
        - PolicyName: SQS-Permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:SendMessage
                Resource: !GetAtt EbsVolumeQueue.Arn
        - PolicyName: CloudWatchLogs-Permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: @BUCKET_NAME@
        S3Key: @ZIP_OBJ_NAME@
      Description: EBS Snapshot Manager Instance Manager
      Environment:
        Variables:
          DEFAULT_RETENTION: !Ref DefaultRetention
          FREQUENCY_TAG_NAME: !Ref FrequencyTagName
          RETENTION_TAG_NAME: !Ref RetentionTagName
          VOLUME_QUEUE_URL: !Ref EbsVolumeQueue
      Handler: ebs_snapshot_manager.lambda_handler
      MemorySize: 512
      ReservedConcurrentExecutions: 2
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
      Timeout: 300
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledInvocation.Arn
  ScheduledInvocation:
    Type: AWS::Events::Rule
    Properties:
      Description: Invoke the EBS Snapshot Manager every 5 minutes
      ScheduleExpression: "rate(5 minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: InstanceManager
          Input: "{\"Action\": \"CheckInstances\"}"
        - Arn: !GetAtt LambdaFunction.Arn
          Id: VolumeManager
          Input: "{\"Action\": \"CheckVolumes\"}"
